---
title: "Cross-validation object (cvo)"
author: "Vilmantas Gegzna"
date: "`r Sys.Date()` (v`r packageVersion('manyROC')`)"
output:
    rmarkdown::html_vignette: 
        toc: yes
        number_sections: yes
vignette: >
  %\VignetteIndexEntry{manyROC_3_cvo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r options, echo = FALSE, message = FALSE, warning = FALSE}
optDEF <- knitr::opts_chunk$get()
knitr::opts_chunk$set(collapse = FALSE, comment = "#>")

knitr::opts_chunk$set(fig.width = 6, fig.align = 'center')
```

Load packages

```{r Load packages, include = FALSE, message = FALSE, warning = FALSE}
library(manyROC)
```
```{r}
library(manyROC)
```

`cvo_create_folds`
================================================


```{r}
# clear()

# Make some data
DataSet1 <- data.frame(ID = rep(1:20, each = 2),
                       gr = gl(4, 10, labels = LETTERS[1:4]),
                       .row = 1:40)

# Set parameters
nFolds = 5

# Explore data
str(DataSet1)

# table(DataSet1[,c("gr","ID")])
# summary(DataSet1)
```

`createFolds2` and `stratifiedFolds` is the same function with different names
```{r}

set.seed(1)
cvo_create_folds(block_by = DataSet1$ID, k = nFolds)
```

When variable names from data frame are provided:
```{r}
Folds1_a <- cvo_create_folds(data = DataSet1,
                             stratify_by = "gr",
                             block_by = "ID",
                             nFolds,
                             returnTrain = FALSE)
# str(Folds1_a)
cvo_test_bs(Folds1_a,
            stratify_by = "gr",
            block_by = "ID",
            data = DataSet1)

```

When "free" variables are provided:
```{r}
Folds1_b <- cvo_create_folds(stratify_by = DataSet1$gr,
                             block_by = DataSet1$ID,
                             k = nFolds,
                             returnTrain = FALSE)
# str(Folds1_b)
cvo_test_bs(Folds1_b,
            stratify_by = "gr",
            block_by = "ID",
            data = DataSet1
)
```

Not blocked but stratified:
```{r}
Folds1_c <- cvo_create_folds(stratify_by = DataSet1$gr,
                             k = nFolds,
                             returnTrain = FALSE)
# str(Folds1_c)
cvo_test_bs(Folds1_c, 
            stratify_by = "gr",
            block_by = "ID",
            data = DataSet1)
```

Blocked but not stratified:
```{r}
Folds1_d <- cvo_create_folds(block_by = DataSet1$ID,
                             k = nFolds,
                             returnTrain = FALSE)
# str(Folds1_d)
cvo_test_bs(Folds1_d,
            stratify_by = "gr",
            block_by = "ID",
            DataSet1)
```

