---
title: "Introduction to `manyROC`"
author: "Vilmantas Gegzna"
date: "`r Sys.Date()` (v`r packageVersion('manyROC')`)"
output:
    rmarkdown::html_vignette: 
        toc: yes
        number_sections: yes
vignette: >
  %\VignetteIndexEntry{1 manyROC Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteDepends{glue}
  %\VignetteEncoding{UTF-8}
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = FALSE,
                      comment = "#>",
                      fig.align = 'center',
                      fig.width = 6)
optDEF <- knitr::opts_chunk$get()
```

Load package

```{r Load main package, message = FALSE, warning = FALSE}
library(manyROC)
```

// Introduction is being prepared... //
============================================================================= 

...

```{r}
# Make some data
set.seed(1)
(x_ <- rnorm(10))
(gr_ <- gl(n = 2, k = 5, length = 10, labels = c("H","S")))

# Explore the functions
roc_analysis(x_, gr_)
```

<!-- # ```{r session info} -->
<!-- # devtools::session_info() -->
<!-- # ``` -->
